### ISSUE TITLE
Add buttons for playing, recording and synchronizing in the Android app

### ISSUE THREAD

**Issue by hesa** [hesa/coachassistant#38] opened 2016-02-12 22:37 UTC

**Comment by jonkri** [comment] 2016-02-20 17:56
Is this a duplicate of #34, or am I misunderstanding something? :)

**Comment by hesa** [comment] 2016-03-08 21:02
Have implemented the code to this (not really expecting Nobel prize for this one) and really horribly looking button beside the preview window. Works ok, nice looking? No!

I need to discuss how to proceed with this.

**Comment by jonkri** [comment] 2016-03-21 08:21
Nice! What do you think of the possibility of putting the instruction video and the name of the training phase to the right of the video in preview and under the video in landscape? I guess we should figure out the ratio of the video and find a proper height (width in portrait) for it and see!

**Comment by jonkri** [comment] 2016-03-21 08:55
Assigning myself so that I'll remember to bring this up for discussion.

**Comment by jonkri** [comment] 2016-03-22 13:10
![2016-03-22](https://cloud.githubusercontent.com/assets/777056/13952610/b70f73ac-f037-11e5-96b9-0e59f7c613e6.jpg)

**Comment by jonkri** [comment] 2016-03-22 13:10
https://design.google.com/icons/

**Comment by jonkri** [comment] 2016-03-22 13:13
* Landscape and portrait previews should have the same ratio and area
* We will probably want play and record buttons in the title bar (see the icon link above)
* The record button should probably be red, and the play button some other color
* We want to have a warning prior to overriding a training phase video

**Comment by hesa** [comment] 2016-03-22 13:17
https://design.google.com/icons/
 * play arrow / play arrow filled
 * fiber manual record

**Comment by jonkri** [comment] 2016-05-12 11:28
We can have these buttons together in the toolbar.

**Comment by jonkri** [comment] 2016-05-12 11:33
(Possibly animated refresh icon next to play and record button. And by refresh we mean uploading videos. We might want to block usage of the app while syncing if the limited IO capabilities results in bad quality video.)

**Comment by jonkri** [comment] 2016-05-27 11:30
This is sorted.

**Closed by jonkri** 2016-05-27 11:30 UTC
Labels: 1.0, android
